# Generated by Django 4.1.7 on 2023-06-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('ENT', 'ENT'), ('CD', 'Cardiologist'), ('NE', 'Neurologist'), ('ONC', 'Oncologist'), ('ORT', 'Orthologist'), ('DNT', 'Dentist'), ('PHY', 'Physician')], max_length=3, null=True),
        ),
    ]
