# Generated by Django 4.1.7 on 2023-06-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('STF', 'Staff'), ('DR', 'Doctor')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('ENT', 'ENT'), ('CD', 'Cardiologist'), ('NE', 'Neurologist'), ('ONC', 'Oncologist'), ('ORT', 'Orthologist'), ('DNT', 'Dentist'), ('PHY', 'Physician')], max_length=3, null=True),
        ),
    ]
