# Generated by Django 4.1.7 on 2023-06-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_profession_alter_profile_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
    ]
