# Generated by Django 4.1.7 on 2023-06-06 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time_wanted', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening'), ('A', 'Either Morning or Evening')], max_length=1)),
                ('appointment_time', models.TimeField(default='12:00')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('CN', 'Canceled'), ('CMP', 'Completed')], default='P', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialization', models.CharField(blank=True, choices=[('N', 'None'), ('ENT', 'ENT'), ('CD', 'Cardiologist'), ('NE', 'Neurologist'), ('ONC', 'Oncologist'), ('ORT', 'Orthologist'), ('DNT', 'Dentist'), ('PHY', 'Physician')], max_length=3, null=True)),
                ('contact_info', models.IntegerField()),
                ('appointments', models.ManyToManyField(blank=True, related_name='doctors', to='Med.appointment')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='Doctors_for_appnt',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to='Med.doctor_profiles'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
