# Generated by Django 4.1.7 on 2023-06-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0002_alter_appointment_doctors_for_appnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_profiles',
            name='appointments',
        ),
    ]
