# Generated by Django 4.1.7 on 2023-06-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0005_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='Med.prescription'),
        ),
    ]
