# Generated by Django 4.1.7 on 2023-06-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0007_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Pay_amount',
            field=models.IntegerField(default=0),
        ),
    ]
